services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build: ./backend
    command: celery -A workd_project worker -l info
    env_file: .env
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
