# Generated by Django 5.1 on 2026-04-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.BigIntegerField(verbose_name='보증금')),
                ('monthly_rent', models.BigIntegerField(default=0, verbose_name='월세')),
                ('start_date', models.DateField(verbose_name='계약 시작일')),
                ('end_date', models.DateField(verbose_name='계약 종료일')),
                ('move_in_date', models.DateField(verbose_name='입주일')),
                ('special_terms', models.TextField(blank=True, verbose_name='특약사항')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('landlord_confirmed', '임대인 확인'), ('tenant_confirmed', '임차인 확인'), ('both_confirmed', '쌍방 확인'), ('agent_verified', '중개사 확인'), ('signed', '서명 완료'), ('active', '계약 진행중'), ('expiring', '만기 임박'), ('expired', '만기'), ('renewed', '갱신'), ('terminated', '해지')], default='draft', max_length=20)),
                ('landlord_confirmed', models.BooleanField(default=False)),
                ('landlord_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_confirmed', models.BooleanField(default=False)),
                ('tenant_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_verified', models.BooleanField(default=False)),
                ('agent_verified_at', models.DateTimeField(blank=True, null=True)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='contracts/signed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_agent', to=settings.AUTH_USER_MODEL, verbose_name='공인중개사')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계약서',
                'verbose_name_plural': '계약서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_validity', models.BooleanField(default=False, verbose_name='계약서 적정성')),
                ('property_status', models.BooleanField(default=False, verbose_name='물건지 현황')),
                ('commission_calc', models.BooleanField(default=False, verbose_name='중개보수 산정')),
                ('disclosure_form', models.BooleanField(default=False, verbose_name='확인·설명서')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_verification', to='contracts.contract')),
            ],
            options={
                'verbose_name': '중개사 확인',
            },
        ),
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_deposit', models.BigIntegerField(verbose_name='합의 보증금')),
                ('agreed_rent', models.BigIntegerField(default=0, verbose_name='합의 월세')),
                ('agreed_start_date', models.DateField(verbose_name='계약 시작일')),
                ('agreed_end_date', models.DateField(verbose_name='계약 종료일')),
                ('agreed_move_in_date', models.DateField(verbose_name='입주일')),
                ('safety_insurance', models.BooleanField(default=False, verbose_name='보증보험')),
                ('safety_notary', models.BooleanField(default=False, verbose_name='공증')),
                ('safety_mortgage', models.BooleanField(default=False, verbose_name='근저당 설정')),
                ('deposit_agreed', models.BooleanField(default=False)),
                ('period_agreed', models.BooleanField(default=False)),
                ('landlord_agreed', models.BooleanField(default=False)),
                ('landlord_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_agreed', models.BooleanField(default=False)),
                ('tenant_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('deposit_agreed', '보증금 합의'), ('period_agreed', '기간 합의'), ('landlord_agreed', '임대인 동의'), ('tenant_agreed', '임차인 동의'), ('both_agreed', '쌍방 합의'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계약 합의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.contractagreement'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '진행중'), ('viewing_scheduled', '방문예정'), ('closed', '종료')], default='active', max_length=20)),
                ('viewing_date', models.DateTimeField(blank=True, null=True, verbose_name='방문 일정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_received', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문의',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('tenant', '임차인'), ('landlord', '임대인'), ('system', '시스템')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contracts.inquiry')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(choices=[('landlord', '임대인'), ('tenant', '임차인'), ('agent', '공인중개사')], max_length=10)),
                ('signature_data', models.TextField(verbose_name='서명 데이터 (base64)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='서명 IP')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '전자서명',
                'unique_together': {('contract', 'signer_role')},
            },
        ),
    ]
