# Generated by Django 5.1 on 2026-04-08 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='매물명')),
                ('address', models.TextField(verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, max_length=200, verbose_name='상세주소')),
                ('property_type', models.CharField(choices=[('apartment', '아파트'), ('villa', '빌라'), ('multi_family', '다세대'), ('officetel', '오피스텔'), ('mixed_use', '주상복합')], max_length=20, verbose_name='매물유형')),
                ('size_sqm', models.FloatField(verbose_name='면적 (㎡)')),
                ('floor', models.CharField(max_length=20, verbose_name='층수')),
                ('built_year', models.IntegerField(verbose_name='건축년도')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('deposit', models.BigIntegerField(verbose_name='보증금 (원)')),
                ('monthly_rent', models.BigIntegerField(default=0, verbose_name='월세 (원)')),
                ('risk_grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='리스크 등급')),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='안전도 점수')),
                ('is_insurable', models.BooleanField(default=False, verbose_name='보증보험 가입 가능')),
                ('is_available', models.BooleanField(default=True, verbose_name='계약 가능')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 매물')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='임대인')),
            ],
            options={
                'verbose_name': '매물',
                'verbose_name_plural': '매물 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('tag_type', models.CharField(choices=[('positive', '긍정'), ('warning', '경고'), ('danger', '위험')], default='positive', max_length=20)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='RiskScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('overall_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('overall_score', models.IntegerField(default=0)),
                ('mortgage_status', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('mortgage_detail', models.TextField(blank=True)),
                ('ownership_status', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('ownership_detail', models.TextField(blank=True)),
                ('seizure_status', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('seizure_detail', models.TextField(blank=True)),
                ('jeonse_ratio', models.FloatField(default=0, verbose_name='전세가율 (%)')),
                ('jeonse_status', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('landlord_multi_house', models.IntegerField(default=0, verbose_name='임대인 보유주택 수')),
                ('landlord_status', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('tax_delinquency_status', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('tax_delinquency_detail', models.TextField(blank=True)),
                ('hug_available', models.BooleanField(default=False, verbose_name='HUG 가입 가능')),
                ('sgi_available', models.BooleanField(default=False, verbose_name='SGI 가입 가능')),
                ('loan_available', models.BooleanField(default=False, verbose_name='전세대출 가능')),
                ('empty_house_risk', models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=10)),
                ('empty_house_detail', models.TextField(blank=True)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scans', to='properties.property')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리스크 스캔',
                'verbose_name_plural': '리스크 스캔 목록',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
