# Generated by Django 5.1 on 2026-04-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('expiry_alert', '만기 안내'), ('renewal', '계약 갱신'), ('info_change', '정보 변경'), ('insurance_renewal', '보증보험 갱신'), ('market_report', '시세 리포트'), ('mortgage_release', '근저당 말소'), ('deposit_return', '보증금 반환'), ('dispute', '분쟁 대응')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('active', '활성'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(verbose_name='예정일')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract')),
            ],
            options={
                'verbose_name': '계약 이벤트',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('kakao', '알림톡'), ('sms', '문자'), ('email', '이메일'), ('push', '푸시')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '대기'), ('sent', '발송'), ('delivered', '수신'), ('failed', '실패')], default='pending', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('prepaid', '선불 (매월 초)'), ('postpaid', '후불 (매월 말)')], default='prepaid', max_length=10)),
                ('due_date', models.DateField(verbose_name='납부일')),
                ('amount', models.BigIntegerField(verbose_name='납부 금액')),
                ('status', models.CharField(choices=[('pending', '예정'), ('upcoming', '납부 예정'), ('paid', '납부 완료'), ('overdue', '미납')], default='pending', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='실제 납부일')),
                ('paid_amount', models.BigIntegerField(default=0, verbose_name='실제 납부 금액')),
                ('reminder_3days_sent', models.BooleanField(default=False, verbose_name='3일 전 알림')),
                ('reminder_dueday_sent', models.BooleanField(default=False, verbose_name='당일 알림')),
                ('overdue_reminder_sent', models.BooleanField(default=False, verbose_name='미납 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedules', to='contracts.contract')),
            ],
            options={
                'verbose_name': '납부 스케줄',
                'ordering': ['due_date'],
            },
        ),
    ]
