# Generated by Django 5.1 on 2026-04-08 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('hug', 'HUG (주택도시보증공사)'), ('sgi', 'SGI (서울보증보험)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '신청 대기'), ('applied', '신청 완료'), ('reviewing', '심사 중'), ('approved', '승인'), ('rejected', '거절'), ('active', '가입 완료'), ('expiring', '만기 임박'), ('expired', '만기'), ('renewed', '갱신')], default='pending', max_length=20)),
                ('coverage_amount', models.BigIntegerField(verbose_name='보장 금액')),
                ('premium', models.BigIntegerField(default=0, verbose_name='보험료')),
                ('premium_rate', models.FloatField(default=0.00128, verbose_name='보험료율')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='보험 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='보험 종료일')),
                ('policy_number', models.CharField(blank=True, max_length=50, verbose_name='증권번호')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_apps', to='contracts.contract')),
            ],
            options={
                'verbose_name': '보증보험',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MortgageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '신청 대기'), ('lawyer_matched', '법무사 매칭'), ('processing', '처리 중'), ('registered', '설정 완료'), ('released', '말소 완료'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('amount', models.BigIntegerField(verbose_name='설정 금액')),
                ('lawyer_name', models.CharField(blank=True, max_length=50, verbose_name='법무사명')),
                ('lawyer_phone', models.CharField(blank=True, max_length=20)),
                ('fee', models.BigIntegerField(default=0, verbose_name='설정 비용')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_apps', to='contracts.contract')),
            ],
            options={
                'verbose_name': '근저당 설정',
            },
        ),
        migrations.CreateModel(
            name='NotaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '신청 대기'), ('matched', '공증사무소 매칭'), ('scheduled', '일정 확정'), ('completed', '공증 완료'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('notary_office', models.CharField(blank=True, max_length=100, verbose_name='공증사무소')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('fee', models.BigIntegerField(default=0, verbose_name='공증 비용')),
                ('document', models.FileField(blank=True, null=True, upload_to='notary/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notary_apps', to='contracts.contract')),
            ],
            options={
                'verbose_name': '공증 신청',
            },
        ),
    ]
